use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# WorkerWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :worker, WorkerWeb.Endpoint,
  load_from_system_env: true,
  http: [port: "4008"],
  secret_key_base: "${SECRET_KEY_BASE}",
  url: [host: "${HOST}", port: "4008"], # This is critical for ensuring web-sockets properly authorize.
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: "."

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :worker, WorkerWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :worker, WorkerWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :worker, WorkerWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.

config :exq,
  host: "${REDIS_HOST}",
  port: "${REDIS_PORT}",
  namespace: "exq",
  queues: [
    {"member_activation_job", 5},
    {"benefit_migration_job", 3},
    {"product_migration_job", 3},
    {"account_migration_job", 3},
    {"member_migration_job", 3},
    {"member_existing_migration_job", 3},
    {"benefit_batch_migration_job", 3},
    {"check_job_acu_schedules_job", 10},
    {"product_batch_migration_job", 3},
    {"member_batch_migration_job", 3},
    {"member_batch_existing_migration_job", 3},
    {"create_member_job", 20},
    {"create_member_existing_job", 20},
    {"create_benefit_job", 10},
    {"create_product_job", 10},
    {"create_account_job", 10},
    {"notification_job", 3},
    {"acu_schedule_member_job", 15},
    {"availed_loa_job", 10},
    {"forfeited_loa_status_job", 4},
    {"member_batch_migration_job", 5},
    {"balancing_file_job", 1},
    {"trigger_generate_claims_file_job", 1},
    {"generate_claims_file_job", 1},
    {"update_migrated_claim_job", 10},
    {"account_single_migration_job", 3},
    {"member_batch_upload_job", 10},
    {"member_parser_job", 20},
    {"job_checker", 10},
    {"notification_job", 3},
    {"generate_member_card_no_job", 50},
    {"member_with_user_job", 3},
    {"create_member_with_user_job", 20}
  ],
  scheduler_enable: true,
  max_retries: 0,
  mode: :default

config :exq_ui,
  web_port: 4010,
  web_namespace: "${EXQ_UI_NAMESPACE}",
  server: true
